"""initial schema

Revision ID: 619ed1bd3289
Revises: 
Create Date: 2026-09-17 19:36:15.443074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '619ed1bd3289'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('role_title', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('source_ref', sa.String(length=512), nullable=True),
    sa.Column('jd_text', sa.Text(), nullable=True),
    sa.Column('jd_url', sa.String(length=1024), nullable=True),
    sa.Column('recruiter_name', sa.String(length=255), nullable=True),
    sa.Column('recruiter_contact', sa.String(length=255), nullable=True),
    sa.Column('received_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resume_job_slug', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('manual', 'gmail', 'linkedin')", name='ck_leads_source'),
    sa.CheckConstraint("status IN ('new', 'tailoring', 'tailored', 'applied', 'interviewing', 'rejected', 'offer', 'withdrawn', 'archived')", name='ck_leads_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resume_job_slug')
    )
    op.create_index('ix_leads_created_at', 'leads', ['created_at'], unique=False)
    op.create_index('ix_leads_status', 'leads', ['status'], unique=False)
    op.create_table('interview_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('location_or_link', sa.String(length=512), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('manual', 'gmail_parsed')", name='ck_interview_events_source'),
    sa.CheckConstraint("type IN ('phone_screen', 'technical', 'onsite', 'call', 'other')", name='ck_interview_events_type'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_interview_events_lead_id_scheduled_at', 'interview_events', ['lead_id', 'scheduled_at'], unique=False)
    op.create_table('status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.String(length=20), nullable=True),
    sa.Column('new_status', sa.String(length=20), nullable=False),
    sa.Column('changed_by', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("changed_by IN ('system', 'user', 'agent')", name='ck_status_history_changed_by'),
    sa.CheckConstraint("new_status IN ('new', 'tailoring', 'tailored', 'applied', 'interviewing', 'rejected', 'offer', 'withdrawn', 'archived')", name='ck_status_history_new_status'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_status_history_lead_id', 'status_history', ['lead_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_status_history_lead_id', table_name='status_history')
    op.drop_table('status_history')
    op.drop_index('ix_interview_events_lead_id_scheduled_at', table_name='interview_events')
    op.drop_table('interview_events')
    op.drop_index('ix_leads_status', table_name='leads')
    op.drop_index('ix_leads_created_at', table_name='leads')
    op.drop_table('leads')
    # ### end Alembic commands ###
