"""email ingestion tables

Revision ID: 44d7a736d1e8
Revises: 619ed1bd3289
Create Date: 2026-09-17 20:41:01.275480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44d7a736d1e8'
down_revision: Union[str, Sequence[str], None] = '619ed1bd3289'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('gmail_thread_id', sa.String(length=64), nullable=False),
    sa.Column('gmail_history_id', sa.BigInteger(), nullable=True),
    sa.Column('last_message_id', sa.String(length=64), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gmail_thread_id')
    )
    op.create_index('ix_email_threads_lead_id', 'email_threads', ['lead_id'], unique=False)
    op.create_table('email_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('gmail_message_id', sa.String(length=64), nullable=False),
    sa.Column('from_addr', sa.String(length=512), nullable=True),
    sa.Column('subject', sa.String(length=1024), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('classification', sa.String(length=20), nullable=True),
    sa.Column('classification_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("classification IS NULL OR classification IN ('job_lead', 'not_job_lead', 'skipped_prefilter')", name='ck_email_messages_classification'),
    sa.CheckConstraint("direction IN ('inbound', 'outbound')", name='ck_email_messages_direction'),
    sa.CheckConstraint('classification_confidence IS NULL OR (classification_confidence >= 0 AND classification_confidence <= 1)', name='ck_email_messages_confidence_range'),
    sa.ForeignKeyConstraint(['thread_id'], ['email_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gmail_message_id')
    )
    op.create_index('ix_email_messages_received_at', 'email_messages', ['received_at'], unique=False)
    op.create_index('ix_email_messages_thread_id', 'email_messages', ['thread_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_email_messages_thread_id', table_name='email_messages')
    op.drop_index('ix_email_messages_received_at', table_name='email_messages')
    op.drop_table('email_messages')
    op.drop_index('ix_email_threads_lead_id', table_name='email_threads')
    op.drop_table('email_threads')
    # ### end Alembic commands ###
