"""email message location fields

Revision ID: 091fd912524f
Revises: 44d7a736d1e8
Create Date: 2026-09-17 20:57:06.310541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '091fd912524f'
down_revision: Union[str, Sequence[str], None] = '44d7a736d1e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_messages', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('email_messages', sa.Column('location_ok', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_messages', 'location_ok')
    op.drop_column('email_messages', 'location')
    # ### end Alembic commands ###
